#!/usr/bin/env python3
"""Generate tokens/brand.css from tokens/brand.tokens.json.

Light is the default theme; the system preference switches to dark, and
`data-theme="light"` or `"dark"` on the root element overrides it. Every
property is `--sx-*`.

  python3 scripts/build_tokens.py          # write tokens/brand.css
  python3 scripts/build_tokens.py --check  # fail if tokens/brand.css is stale
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tokens/brand.tokens.json"
OUT = ROOT / "tokens/brand.css"


def value(token: dict) -> str:
    v = token["$value"]
    if token["$type"] == "gradient":
        angle = token.get("$extensions", {}).get("com.sylphx.angle", "180deg")
        stops = ", ".join(f"{s['color']} {round(s['position'] * 100)}%" for s in v)
        return f"linear-gradient({angle}, {stops})"
    if token["$type"] == "cubicBezier":
        return "cubic-bezier(" + ", ".join(str(x) for x in v) + ")"
    if token["$type"] == "fontFamily":
        return ", ".join(f'"{f}"' if " " in f else f for f in v)
    return v


def flatten(group: dict, prefix: str) -> list[tuple[str, str]]:
    out = []
    for key, node in group.items():
        if key.startswith("$"):
            continue
        name = f"{prefix}-{key}"
        if "$value" in node:
            out.append((name, value(node)))
        else:
            out += flatten(node, name)
    return out


def render() -> str:
    t = json.loads(SRC.read_text())
    common = []
    for group in ("mark", "font", "radius", "space", "size", "motion", "icon"):
        common += flatten(t[group], f"--sx-{group}")
    light = flatten(t["theme"]["light"], "--sx")
    dark = flatten(t["theme"]["dark"], "--sx")
    rows = lambda r: "".join(f"\t{k}: {v};\n" for k, v in r)
    return (
        "/* Generated by scripts/build_tokens.py from tokens/brand.tokens.json. Do not edit. */\n"
        ":root {\n" + rows(common + light) + "\tcolor-scheme: light;\n}\n"
        "@media (prefers-color-scheme: dark) {\n\t:root:not([data-theme=\"light\"]) {\n"
        + rows(dark).replace("\t", "\t\t") + "\t\tcolor-scheme: dark;\n\t}\n}\n"
        ':root[data-theme="dark"] {\n' + rows(dark) + "\tcolor-scheme: dark;\n}\n"
    )


if __name__ == "__main__":
    css = render()
    if "--check" in sys.argv:
        if OUT.read_text() != css:
            sys.exit("tokens/brand.css is stale: run python3 scripts/build_tokens.py")
    else:
        OUT.write_text(css)
